### PR TITLE
Hotfix clear language keys

### PR DESCRIPTION
**Pull request by zonky2**
Hotfix clear language keys

### CODE REVIEW

**Review by discordier — APPROVED** [review]
While I am unsure if these are the only obsolete language keys, I can confirm that these have to go away.

**Comment by zonky2** [comment]
we have only two keys: type and hide tablehead...

**Comment by discordier** [comment]
There is also `$GLOBALS['TL_LANG']['tl_metamodel_rendersetting']['tablemulti_hide_tablehead']` but I seem to remeber we checked that this one is ok.

**Comment by zonky2** [comment]
> hide tablehead

mean "tablemulti_hide_tablehead"

**Pull request merged**
